abaporu-C/GROW-POS

GROW-CRM/Data/GROWSeedData.cs
GROW-CRM/Models/Household.cs
GROW-CRM/Models/Member.cs
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml
GROW-CRM/Views/Households/Create.cshtml

Closes #23

---

GROW-CRM/Controllers/HouseholdMembersController.cs
GROW-CRM/Models/Household.cs
GROW-CRM/Views/HouseholdMembers/Index.cshtml
GROW-CRM/Views/Households/Create.cshtml

LICO verification automated // Fixed Issue #22

---

GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Index.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml

Closes #31 
Closes #32 
Closes #33 
Closes #34

Minor UI issues fixed // Issues #31 #32 #33 #34

---

GROW-CRM/Controllers/HouseholdsController.cs
GROW-CRM/Models/Member.cs
GROW-CRM/Views/Households/Index.cshtml
GROW-CRM/Views/Members/Details.cshtml

Closes #37 
Closes #38 
Closes #41

Minor UI issues // Fixed Issues #37 #38 #41

---

GROW-CRM/Controllers/MembersController.cs
GROW-CRM/Views/Members/Details.cshtml

Member Detail View UI Fixes // Issue #40

---

GROW-CRM/Controllers/HouseholdMembersController.cs
GROW-CRM/Controllers/HouseholdsController.cs
GROW-CRM/Data/GROWMigrations/20220211143345_Initial.Designer.cs
GROW-CRM/Data/GROWMigrations/20220211143345_Initial.cs
GROW-CRM/Data/GROWMigrations/GROWContextModelSnapshot.cs
GROW-CRM/Models/Household.cs
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Index.cshtml
GROW-CRM/Views/Households/Create.cshtml
GROW-CRM/Views/Households/Delete.cshtml
GROW-CRM/Views/Households/Details.cshtml
GROW-CRM/Views/Households/Edit.cshtml
GROW-CRM/Views/Households/Index.cshtml
GROW-CRM/Views/Members/Create.cshtml
GROW-CRM/Views/Reports/SelectedReport.cshtml

Hey @abaporu-C . Take a look please. 
Closed Issues:
#96 
#57 
#59 
#61 
#64 
#80 
FridaySerge is done here. for now =D

Friday Serge is Done here

---

GROW-CRM/Controllers/HouseholdMembersController.cs
GROW-CRM/Data/GROWSeedData.cs
GROW-CRM/Models/Member.cs
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Details.cshtml
GROW-CRM/Views/HouseholdMembers/Remove.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml
GROW-CRM/Views/Members/Details.cshtml

Fixed issue #95, Check Box For Consent Added

---

GROW-CRM/Controllers/HouseholdsController.cs
GROW-CRM/Controllers/ReportsController.cs
GROW-CRM/Views/Home/Index.cshtml
GROW-CRM/Views/HouseholdMembers/Index.cshtml
GROW-CRM/Views/HouseholdMembers/Remove.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml
GROW-CRM/Views/Households/Create.cshtml
GROW-CRM/Views/Households/Index.cshtml
GROW-CRM/Views/Members/Delete.cshtml
GROW-CRM/Views/Members/Details.cshtml
GROW-CRM/Views/Members/Index.cshtml
GROW-CRM/Views/Reports/SelectedReport.cshtml
GROW-CRM/Views/Shared/_Layout.cshtml

Override ID + Headings Checked

---

GROW-CRM/Views/Reports/Partial/_Mapping.cshtml

Issue #106 fixed / Accordion in mapping fixed

---

GROW-CRM/Controllers/HouseholdsController.cs
GROW-CRM/Views/Households/Create.cshtml

Closes Issue #67

---

GROW-CRM/Controllers/Helpers/ReportsHelper.cs

Fixed issue #117

---

GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml
GROW-CRM/Views/Households/Create.cshtml
GROW-CRM/wwwroot/css/site.css

Household create view enhancement

---

GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml
GROW-CRM/Views/Households/Create.cshtml
GROW-CRM/Views/Households/Edit.cshtml

Added Popovers to members and household UI

Added popovers to household and members views

---

GROW-CRM/Controllers/HouseholdMembersController.cs
GROW-CRM/Models/Member.cs
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Remove.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml
GROW-CRM/Views/Members/Delete.cshtml
GROW-CRM/Views/Members/Details.cshtml

Member model update / Fixes Issue #71

---

GROW-CRM/Views/HouseholdMembers/Index.cshtml

LICO help modal added

---

GROW-CRM/Controllers/HealthIssueTypesController.cs
GROW-CRM/Controllers/LookupsController.cs
GROW-CRM/Views/DietaryRestrictions/Create.cshtml
GROW-CRM/Views/HealthIssueTypes/Create.cshtml
GROW-CRM/Views/HealthIssueTypes/Delete.cshtml
GROW-CRM/Views/HealthIssueTypes/Details.cshtml
GROW-CRM/Views/HealthIssueTypes/Edit.cshtml
GROW-CRM/Views/HealthIssueTypes/Index.cshtml
GROW-CRM/Views/Households/Create.cshtml
GROW-CRM/Views/Lookups/Index.cshtml
GROW-CRM/Views/Lookups/_HealthIssueTypes.cshtml

Changed the ID's to match the city and province correctly.

Changed ids for default address

---

GROW-CRM/Controllers/DietaryRestrictionsController.cs
GROW-CRM/Views/DietaryRestrictions/Create.cshtml
GROW-CRM/Views/DietaryRestrictions/Edit.cshtml

Fixed Issue #152

---

GROW-CRM/Views/Households/Create.cshtml

Fixed bug where disabled fields in Household/Create don't POST a value.

fixed create household bug

---

GROW-CRM/Views/Categories/Details.cshtml
GROW-CRM/Views/Categories/Index.cshtml
GROW-CRM/Views/HouseholdMembers/Index.cshtml
GROW-CRM/Views/Items/Details.cshtml
GROW-CRM/Views/Items/Index.cshtml

Fixed the buttons for consistency. Also took the documents and notes from the household index view.

Issue 172 and 175 closed

---

GROW-CRM/Properties/serviceDependencies.json
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/HouseholdMembers/Update.cshtml
GROW-CRM/Views/Households/Create.cshtml
GROW-CRM/Views/Households/Edit.cshtml

Popover fade on unfocus and doesn't refresh page anymore

---

GROW-CRM/Controllers/HouseholdsController.cs

Issue #162 Fixed

---

GROW-CRM/Controllers/Helpers/ReportsHelper.cs

Issue #153 Fixed

---

GROW-CRM/Controllers/OrdersController.cs
GROW-CRM/Data/GROWSeedData.cs
GROW-CRM/Models/Item.cs
GROW-CRM/Models/Order.cs
GROW-CRM/Views/Orders/Create.cshtml
GROW-CRM/Views/Orders/Delete.cshtml
GROW-CRM/Views/Orders/Details.cshtml
GROW-CRM/Views/Orders/Edit.cshtml
GROW-CRM/Views/Orders/Index.cshtml
GROW-CRM/Views/Orders/_CreateOrderModal.cshtml
GROW-CRM/Views/Orders/_OrderItemLists.cshtml

I really hope these are okay. If not I'm gonna cry. Also, My ddl for members isn't working. I copy-pasted the code exactly how you had it in (hopefully) all the right spots. I have no idea what I did wrong.
Any help is much appreciated. I'm sure it's something small :/

Order views and such

---

GROW-CRM/Controllers/Helpers/ReportsHelper.cs
GROW-CRM/Controllers/ReportsController.cs
GROW-CRM/Data/GROWContext.cs
GROW-CRM/ViewModels/ReportsViewModels/CategoriesReport.cs
GROW-CRM/ViewModels/ReportsViewModels/NewItemsReport.cs
GROW-CRM/ViewModels/ReportsViewModels/OrderItemsReport.cs
GROW-CRM/ViewModels/ReportsViewModels/OrdersReport.cs
GROW-CRM/Views/Reports/Partial/_Categories.cshtml
GROW-CRM/Views/Reports/Partial/_NewItems.cshtml
GROW-CRM/Views/Reports/Partial/_Sales.cshtml
GROW-CRM/Views/Reports/SelectedReport.cshtml

Added reports for Sales by Category, All New Sales (Weekly, will expand), and New Items (Weekly, will expand). Still need to build onto the reports and group them like with Demographics instead of having each one be its own page, but everything should be working now at least and shouldn't break anything.

JamesH3 - Basic Sales Reports

---

GROW-CRM/Controllers/OrdersController.cs
GROW-CRM/GROW-CRM.csproj
GROW-CRM/Program.cs
GROW-CRM/Views/Orders/Index.cshtml
GROW-CRM/Views/Orders/_CreateOrderModal.cshtml

Fixes Issue #202 and Issue #203

---

GROW-CRM/Startup.cs

Session Timeout increased to 2h

---

GROW-CRM/Areas/Identity/Pages/Account/Login.cshtml
GROW-CRM/Areas/Identity/Pages/Account/ResetPassword.cshtml
GROW-CRM/Views/Shared/_IdentityLayout.cshtml
GROW-CRM/wwwroot/css/identity.css

Password Toggle Implemented

---

GROW-CRM/Areas/Identity/Pages/Account/Login.cshtml
GROW-CRM/Areas/Identity/Pages/Account/Register.cshtml.cs
GROW-CRM/Controllers/AboutsController.cs
GROW-CRM/Controllers/CategoriesController.cs
GROW-CRM/Controllers/DietaryRestrictionsController.cs
GROW-CRM/Controllers/EmployeesController.cs
GROW-CRM/Controllers/GendersController.cs
GROW-CRM/Controllers/HealthIssueTypesController.cs
GROW-CRM/Controllers/HouseholdMembersController.cs
GROW-CRM/Controllers/HouseholdsController.cs
GROW-CRM/Controllers/ItemsController.cs
GROW-CRM/Controllers/LookupsController.cs
GROW-CRM/Controllers/MemberDocumentsController.cs
GROW-CRM/Controllers/MembersController.cs
GROW-CRM/Controllers/NotificationTypesController.cs
GROW-CRM/Controllers/OrdersController.cs
GROW-CRM/Controllers/PaymentTypesController.cs
GROW-CRM/Controllers/ReportsController.cs
GROW-CRM/Controllers/UserRolesController.cs
GROW-CRM/Data/ApplicationSeedData.cs
GROW-CRM/Data/GROWSeedData.cs
GROW-CRM/Views/HouseholdMembers/Index.cshtml
GROW-CRM/Views/Households/Index.cshtml
GROW-CRM/Views/Members/Index.cshtml
GROW-CRM/Views/Orders/Index.cshtml
GROW-CRM/Views/Shared/_Layout.cshtml

Authorization Feature Applied

---

GROW-CRM/Controllers/NotificationTypesController.cs
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/NotificationTypes/Notification.cshtml

Small changes in the UI for notifications and for add members view

issues #277 and #278

---

GROW-CRM/Controllers/Helpers/ReportsHelper.cs
GROW-CRM/Controllers/ReportsController.cs
GROW-CRM/ViewModels/ReportsViewModels/HouseholdIncomeReport.cs
GROW-CRM/ViewModels/ReportsViewModels/HouseholdInformation.cs
GROW-CRM/Views/Reports/Partial/_Additions.cshtml
GROW-CRM/Views/Reports/Partial/_Demographics.cshtml
GROW-CRM/Views/Reports/Partial/_Income.cshtml
GROW-CRM/Views/Reports/Partial/_Mapping.cshtml
GROW-CRM/Views/Reports/Partial/_NewItems.cshtml
GROW-CRM/Views/Reports/Partial/_Renewal.cshtml
GROW-CRM/Views/Reports/Partial/_Sales.cshtml

Excel formatting fixes and better spacing for download buttons on report views.
Still need to make improvements to the ViewModels and get rid of redundant data but things should look a bit nicer now until then.

Excel Formatting and Button Spacing

---

GROW-CRM/Controllers/EmployeeAccountsController.cs
GROW-CRM/Controllers/EmployeesController.cs
GROW-CRM/Controllers/WebPushController.cs
GROW-CRM/Data/GROWContext.cs
GROW-CRM/GROW-CRM.csproj
GROW-CRM/Models/Employee.cs
GROW-CRM/Models/Subscription.cs
GROW-CRM/VapidKeys
GROW-CRM/ViewModels/EmployeeVM.cs
GROW-CRM/Views/EmployeeAccounts/Details.cshtml
GROW-CRM/Views/EmployeeAccounts/GenerateKeys.cshtml
GROW-CRM/Views/EmployeeAccounts/Push.cshtml
GROW-CRM/Views/Employees/Index.cshtml
GROW-CRM/Views/WebPush/Send.cshtml
GROW-CRM/appsettings.json
GROW-CRM/wwwroot/js/CheckSubscription.js
GROW-CRM/wwwroot/js/CreateSubscription.js
GROW-CRM/wwwroot/js/SendPush.js
GROW-CRM/wwwroot/sw.js

Now the system sends push notifications. Only for employees for now. I'm adapting the members so they can confirm their own user and password so they can also subscribe to notifications. However...It's hard!!! D:

Push Notifications for employes

---

GROW-CRM/Controllers/MembersController.cs
GROW-CRM/Controllers/OrdersController.cs
GROW-CRM/Views/Households/Index.cshtml
GROW-CRM/Views/Items/Index.cshtml
GROW-CRM/Views/Members/Index.cshtml
GROW-CRM/Views/Orders/Index.cshtml

@abaporu-C  thank you for reviewing the previous merge.
This one is the complete #221

#221 Complete

---

GROW-CRM/Controllers/OrdersController.cs

Issue #287 Fixed

---

GROW-CRM/Controllers/OrdersController.cs
GROW-CRM/GROW-CRM.csproj
GROW-CRM/Startup.cs
GROW-CRM/Views/Orders/Create.cshtml
GROW-CRM/Views/Orders/Details.cshtml
GROW-CRM/Views/Orders/Edit.cshtml

PDF download implemented

---

GROW-CRM/Areas/Identity/Pages/Account/Register.cshtml
GROW-CRM/Controllers/CategoriesController.cs
GROW-CRM/Views/Categories/Create.cshtml
GROW-CRM/Views/Cities/Create.cshtml
GROW-CRM/Views/DietaryRestrictions/Create.cshtml
GROW-CRM/Views/Genders/Create.cshtml
GROW-CRM/Views/HealthIssueTypes/Create.cshtml
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/Households/Create.cshtml
GROW-CRM/Views/IncomeSituations/Create.cshtml
GROW-CRM/Views/Items/Create.cshtml
GROW-CRM/Views/Members/Create.cshtml
GROW-CRM/Views/Orders/Create.cshtml
GROW-CRM/Views/PaymentTypes/Create.cshtml
GROW-CRM/Views/Provinces/Create.cshtml
GROW-CRM/Views/Shared/_Layout.cshtml

Fill buttons added

---

GROW-CRM/Controllers/HouseholdMembersController.cs
GROW-CRM/Views/HouseholdMembers/Index.cshtml
GROW-CRM/Views/Shared/_VerificationModal.cshtml

Added verification process

---

GROW-CRM/Controllers/OrdersController.cs
GROW-CRM/Models/Item.cs
GROW-CRM/Views/HouseholdMembers/Add.cshtml
GROW-CRM/Views/Orders/Create.cshtml
GROW-CRM/Views/Orders/_OrderItemLists.cshtml

Stated issues fixed. 
Also, I changed the default sort for the Orders Index to go by Date Descending so that volunteers can see the most recent orders more easily. I felt like this would be a good quality of life change for users, who I can imagine are going to want to see recently entered orders more often than not.

Issues #332, #317, #312, #306, and Orders QoL

---

GROW-CRM/Controllers/OrdersController.cs
GROW-CRM/GROW-CRM.csproj
GROW-CRM/Utilities/EmailService.cs

Issue #305 Fixed
